#+title: Ibrahim's build of st
#+author: Ibrahim Muftee

The suckless terminal stolen from [[https://lukesmith.xyz][Luke Smith]].

* Installation

You should have xlib header files and libharfbuzz build files installed.

#+begin_src shell
  git clone https://github.com/ibrahimmuftee/st
  cd st
  sudo make install
#+end_src


* How to configure dynamically with Xresources

For many key variables, this build of =st= will look for X settings set in
either =~/.Xdefaults= or =~/.Xresources=. You must run =xrdb= on one of these
files to load the settings.

For example, you can define your desired fonts, transparency or colors:

#+begin_src shell
*.font:	Liberation Mono:pixelsize=12:antialias=true:autohint=true;
*.alpha: 0.9
*.color0: #111
...
#+end_src

The `alpha` value (for transparency) goes from `0` (transparent) to `1`
(opaque). There is an example `Xdefaults` file in this respository.

** Colors

To be clear about the color settings:

- This build will use gruvbox colors by default and as a fallback.
- If there are Xresources colors defined, those will take priority.
- But if =wal= has run in your session, its colors will take priority.

Note that when you run =wal=, it will negate the transparency of existing windows, but new windows will continue with the previously defined transparency.

* Notes on Emojis and Special Characters

If st crashes when viewing emojis, install [[https://aur.archlinux.org/packages/libxft-bgra/][libxft-bgra]] from the AUR.

Note that some special characters may appear truncated if too wide. You might want to manually set your prefered emoji/special character font to a lower size in the =config.h= file to avoid this. By default, JoyPixels is used at a smaller size than the usual text.
